const LANGUAGES = [{ code: 'en', label: 'English', flag: '🇬🇧' }, { code: 'tr', label: 'Türkçe', flag: '🇹🇷' }, { code: 'nl', label: 'Dutch', flag: '🇳🇱' }, { code: 'de', label: 'German', flag: '🇩🇪' }, { code: 'es', label: 'Spanish', flag: '🇪🇸' }, { code: 'fr', label: 'French', flag: '🇫🇷' }, { code: 'ar', label: 'Arabic', flag: '🇸🇦' }, { code: 'id', label: 'Indonesian', flag: '🇮🇩' }, { code: 'pt', label: 'Portuguese', flag: '🇵🇹' }, { code: 'hi', label: 'Hindi', flag: '🇮🇳' }, { code: 'ko', label: 'Korean', flag: '🇰🇷' }, { code: 'ja', label: 'Japanese', flag: '🇯🇵' }, { code: 'ru', label: 'Russian', flag: '🇷🇺' }, { code: 'it', label: 'Italian', flag: '🇮🇹' }, { code: 'pl', label: 'Polish', flag: '🇵🇱' }, { code: 'uk', label: 'Ukrainian', flag: '🇺🇦' }];

type LangCode = 'en' | 'tr' | 'nl' | 'de' | 'es' | 'fr' | 'ar' | 'id' | 'pt' | 'hi' | 'ko' | 'ja' | 'ru' | 'it' | 'pl' | 'uk';

const TRANSLATIONS = {
  en:{welcome:"Welcome",addTask:"Add a new task...",habits:"Habits",stats:"Stats",settings:"Settings",appearance:"Appearance",language:"Language",logout:"Log out",assign_to:"Assign to",description:"Description",start_date:"Start date",due_date:"Due date",daily:"Daily",weekly:"Weekly",new_habit:"New habit",habit_name:"Habit name",frequency:"Frequency",days:"Days",end_date:"End date",time:"Time",create:"Create",cancel:"Cancel",save:"Save",delete:"Delete",edit:"Edit",completed:"Completed",search_contact:"Search contact...",notification:"Notification",alarm:"Alarm",every_day:"Every day"},
  tr:{welcome:"Hoş geldin",addTask:"Yeni bir görev ekle...",habits:"Alışkanlıklar",stats:"Özet",settings:"Ayarlar",appearance:"Görünüm",language:"Dil",logout:"Çıkış yap",assign_to:"Kime",description:"Açıklama",start_date:"Başlangıç",due_date:"Son tarih",daily:"Her gün",weekly:"Haftalık",new_habit:"Yeni alışkanlık",habit_name:"Alışkanlık adı",frequency:"Sıklık",days:"Günler",end_date:"Bitiş tarihi",time:"Saat",create:"Oluştur",cancel:"İptal",save:"Kaydet",delete:"Sil",edit:"Düzenle",completed:"Tamamlananlar",search_contact:"Kişi ara...",notification:"Bildirim",alarm:"Alarm",every_day:"Her gün"},
  nl:{welcome:"Welkom",addTask:"Voeg een nieuwe taak toe...",habits:"Gewoontes",stats:"Statistieken",settings:"Instellingen",appearance:"Weergave",language:"Taal",logout:"Uitloggen",assign_to:"Toewijzen aan",description:"Beschrijving",start_date:"Startdatum",due_date:"Einddatum",daily:"Dagelijks",weekly:"Wekelijks",new_habit:"Nieuwe gewoonte",habit_name:"Gewoonte naam",frequency:"Frequentie",days:"Dagen",end_date:"Einddatum",time:"Tijd",create:"Aanmaken",cancel:"Annuleren",save:"Opslaan",delete:"Verwijderen",edit:"Bewerken",completed:"Voltooid",search_contact:"Contact zoeken...",notification:"Notificatie",alarm:"Alarm",every_day:"Elke dag"},
  de:{welcome:"Willkommen",addTask:"Neue Aufgabe hinzufügen...",habits:"Gewohnheiten",stats:"Statistiken",settings:"Einstellungen",appearance:"Darstellung",language:"Sprache",logout:"Abmelden",assign_to:"Zuweisen an",description:"Beschreibung",start_date:"Startdatum",due_date:"Fälligkeitsdatum",daily:"Täglich",weekly:"Wöchentlich",new_habit:"Neue Gewohnheit",habit_name:"Gewohnheitsname",frequency:"Frequenz",days:"Tage",end_date:"Enddatum",time:"Zeit",create:"Erstellen",cancel:"Abbrechen",save:"Speichern",delete:"Löschen",edit:"Bearbeiten",completed:"Abgeschlossen",search_contact:"Kontakt suchen...",notification:"Benachrichtigung",alarm:"Alarm",every_day:"Jeden Tag"},
  es:{welcome:"Bienvenido",addTask:"Agregar una nueva tarea...",habits:"Hábitos",stats:"Estadísticas",settings:"Configuración",appearance:"Apariencia",language:"Idioma",logout:"Cerrar sesión",assign_to:"Asignar a",description:"Descripción",start_date:"Fecha de inicio",due_date:"Fecha límite",daily:"Diario",weekly:"Semanal",new_habit:"Nuevo hábito",habit_name:"Nombre del hábito",frequency:"Frecuencia",days:"Días",end_date:"Fecha de finalización",time:"Hora",create:"Crear",cancel:"Cancelar",save:"Guardar",delete:"Eliminar",edit:"Editar",completed:"Completado",search_contact:"Buscar contacto...",notification:"Notificación",alarm:"Alarma",every_day:"Cada día"},
  fr:{welcome:"Bienvenue",addTask:"Ajouter une nouvelle tâche...",habits:"Habitudes",stats:"Statistiques",settings:"Paramètres",appearance:"Apparence",language:"Langue",logout:"Se déconnecter",assign_to:"Assigner à",description:"Description",start_date:"Date de début",due_date:"Date limite",daily:"Quotidien",weekly:"Hebdomadaire",new_habit:"Nouvelle habitude",habit_name:"Nom de l'habitude",frequency:"Fréquence",days:"Jours",end_date:"Date de fin",time:"Heure",create:"Créer",cancel:"Annuler",save:"Enregistrer",delete:"Supprimer",edit:"Modifier",completed:"Terminé",search_contact:"Rechercher un contact...",notification:"Notification",alarm:"Alarme",every_day:"Chaque jour"},
  ar:{welcome:"مرحبا",addTask:"أضف مهمة جديدة...",habits:"العادات",stats:"الإحصائيات",settings:"الإعدادات",appearance:"المظهر",language:"اللغة",logout:"تسجيل الخروج",assign_to:"تعيين إلى",description:"الوصف",start_date:"تاريخ البدء",due_date:"تاريخ الانتهاء",daily:"يومي",weekly:"أسبوعي",new_habit:"عادة جديدة",habit_name:"اسم العادة",frequency:"التكرار",days:"الأيام",end_date:"تاريخ النهاية",time:"الوقت",create:"إنشاء",cancel:"إلغاء",save:"حفظ",delete:"حذف",edit:"تعديل",completed:"مكتمل",search_contact:"ابحث عن جهة اتصال...",notification:"إشعار",alarm:"منبه",every_day:"كل يوم"},
  id:{welcome:"Selamat datang",addTask:"Tambahkan tugas baru...",habits:"Kebiasaan",stats:"Statistik",settings:"Pengaturan",appearance:"Tampilan",language:"Bahasa",logout:"Keluar",assign_to:"Tugaskan kepada",description:"Deskripsi",start_date:"Tanggal mulai",due_date:"Tanggal jatuh tempo",daily:"Harian",weekly:"Mingguan",new_habit:"Kebiasaan baru",habit_name:"Nama kebiasaan",frequency:"Frekuensi",days:"Hari",end_date:"Tanggal berakhir",time:"Waktu",create:"Buat",cancel:"Batal",save:"Simpan",delete:"Hapus",edit:"Edit",completed:"Selesai",search_contact:"Cari kontak...",notification:"Notifikasi",alarm:"Alarm",every_day:"Setiap hari"},
  pt:{welcome:"Bem-vindo",addTask:"Adicionar nova tarefa...",habits:"Hábitos",stats:"Estatísticas",settings:"Configurações",appearance:"Aparência",language:"Idioma",logout:"Sair",assign_to:"Atribuir a",description:"Descrição",start_date:"Data de início",due_date:"Data de vencimento",daily:"Diário",weekly:"Semanal",new_habit:"Novo hábito",habit_name:"Nome do hábito",frequency:"Frequência",days:"Dias",end_date:"Data final",time:"Hora",create:"Criar",cancel:"Cancelar",save:"Salvar",delete:"Excluir",edit:"Editar",completed:"Concluído",search_contact:"Pesquisar contato...",notification:"Notificação",alarm:"Alarme",every_day:"Todos os dias"},
  hi:{welcome:"स्वागत है",addTask:"एक नया कार्य जोड़ें...",habits:"आदतें",stats:"आँकड़े",settings:"सेटिंग्स",appearance:"दिखावट",language:"भाषा",logout:"लॉग आउट",assign_to:"सौंपें",description:"विवरण",start_date:"प्रारंभ तिथि",due_date:"नियत तिथि",daily:"दैनिक",weekly:"साप्ताहिक",new_habit:"नई आदत",habit_name:"आदत का नाम",frequency:"आवृत्ति",days:"दिन",end_date:"समाप्ति तिथि",time:"समय",create:"बनाएँ",cancel:"रद्द",save:"सहेजें",delete:"हटाएँ",edit:"संपादित करें",completed:"पूर्ण",search_contact:"संपर्क खोजें...",notification:"सूचना",alarm:"अलार्म",every_day:"हर दिन"},
  ko:{welcome:"환영합니다",addTask:"새 작업 추가...",habits:"습관",stats:"통계",settings:"설정",appearance:"모양",language:"언어",logout:"로그아웃",assign_to:"할당 대상",description:"설명",start_date:"시작 날짜",due_date:"마감일",daily:"매일",weekly:"매주",new_habit:"새로운 습관",habit_name:"습관 이름",frequency:"빈도",days:"일",end_date:"종료 날짜",time:"시간",create:"생성",cancel:"취소",save:"저장",delete:"삭제",edit:"편집",completed:"완료됨",search_contact:"연락처 검색...",notification:"알림",alarm:"알람",every_day:"매일"},
  ja:{welcome:"ようこそ",addTask:"新しいタスクを追加...",habits:"習慣",stats:"統計",settings:"設定",appearance:"外観",language:"言語",logout:"ログアウト",assign_to:"割り当て先",description:"説明",start_date:"開始日",due_date:"期限日",daily:"毎日",weekly:"毎週",new_habit:"新しい習慣",habit_name:"習慣名",frequency:"頻度",days:"日",end_date:"終了日",time:"時間",create:"作成",cancel:"キャンセル",save:"保存",delete:"削除",edit:"編集",completed:"完了",search_contact:"連絡先検索...",notification:"通知",alarm:"アラーム",every_day:"毎日"},
  ru:{welcome:"Добро пожаловать",addTask:"Добавить новую задачу...",habits:"Привычки",stats:"Статистика",settings:"Настройки",appearance:"Внешний вид",language:"Язык",logout:"Выйти",assign_to:"Назначить",description:"Описание",start_date:"Дата начала",due_date:"Срок",daily:"Ежедневно",weekly:"Еженедельно",new_habit:"Новая привычка",habit_name:"Название привычки",frequency:"Частота",days:"Дни",end_date:"Дата окончания",time:"Время",create:"Создать",cancel:"Отмена",save:"Сохранить",delete:"Удалить",edit:"Изменить",completed:"Завершено",search_contact:"Поиск контактов...",notification:"Уведомление",alarm:"Будильник",every_day:"Каждый день"},
  it:{welcome:"Benvenuto",addTask:"Aggiungi un nuovo compito...",habits:"Abitudini",stats:"Statistiche",settings:"Impostazioni",appearance:"Aspetto",language:"Lingua",logout:"Disconnettersi",assign_to:"Assegna a",description:"Descrizione",start_date:"Data di inizio",due_date:"Data di scadenza",daily:"Quotidiano",weekly:"Settimanale",new_habit:"Nuova abitudine",habit_name:"Nome dell'abitudine",frequency:"Frequenza",days:"Giorni",end_date:"Data di fine",time:"Ora",create:"Crea",cancel:"Annulla",save:"Salva",delete:"Elimina",edit:"Modifica",completed:"Completato",search_contact:"Cerca contatto...",notification:"Notifica",alarm:"Allarme",every_day:"Ogni giorno"},
  pl:{welcome:"Witamy",addTask:"Dodaj nowe zadanie...",habits:"Nawyki",stats:"Statystyki",settings:"Ustawienia",appearance:"Wygląd",language:"Język",logout:"Wyloguj",assign_to:"Przypisz do",description:"Opis",start_date:"Data rozpoczęcia",due_date:"Termin",daily:"Codziennie",weekly:"Co tydzień",new_habit:"Nowy nawyk",habit_name:"Nazwa nawyku",frequency:"Częstotliwość",days:"Dni",end_date:"Data zakończenia",time:"Czas",create:"Utwórz",cancel:"Anuluj",save:"Zapisz",delete:"Usuń",edit:"Edytuj",completed:"Ukończono",search_contact:"Szukaj kontaktu...",notification:"Powiadomienie",alarm:"Alarm",every_day:"Codziennie"},
  uk:{welcome:"Ласкаво просимо",addTask:"Додати нове завдання...",habits:"Звички",stats:"Статистика",settings:"Налаштування",appearance:"Зовнішній вигляд",language:"Мова",logout:"Вийти",assign_to:"Призначити",description:"Опис",start_date:"Дата початку",due_date:"Кінцевий термін",daily:"Щодня",weekly:"Щотижня",new_habit:"Нова звичка",habit_name:"Назва звички",frequency:"Частота",days:"Дні",end_date:"Дата завершення",time:"Час",create:"Створити",cancel:"Скасувати",save:"Зберегти",delete:"Видалити",edit:"Редагувати",completed:"Завершено",search_contact:"Пошук контакту...",notification:"Сповіщення",alarm:"Будильник",every_day:"Щодня"}
};

const GREETINGS = {
  en:{morning:"Good morning",afternoon:"Good afternoon",evening:"Good evening"},
  tr:{morning:"Günaydın",afternoon:"Tünaydın",evening:"İyi akşamlar"},
  nl:{morning:"Goedemorgen",afternoon:"Goedemiddag",evening:"Goedenavond"},
  de:{morning:"Guten Morgen",afternoon:"Guten Nachmittag",evening:"Guten Abend"},
  es:{morning:"Buenos días",afternoon:"Buenas tardes",evening:"Buenas noches"},
  fr:{morning:"Bonjour",afternoon:"Bon après-midi",evening:"Bonsoir"},
  ar:{morning:"صباح الخير",afternoon:"مساء الخير",evening:"مساء الخير"},
  id:{morning:"Selamat pagi",afternoon:"Selamat siang",evening:"Selamat malam"},
  pt:{morning:"Bom dia",afternoon:"Boa tarde",evening:"Boa noite"},
  hi:{morning:"सुप्रभात",afternoon:"नमस्कार",evening:"शुभ संध्या"},
  ko:{morning:"좋은 아침",afternoon:"좋은 오후",evening:"좋은 저녁"},
  ja:{morning:"おはようございます",afternoon:"こんにちは",evening:"こんばんは"},
  ru:{morning:"Доброе утро",afternoon:"Добрый день",evening:"Добрый вечер"},
  it:{morning:"Buongiorno",afternoon:"Buon pomeriggio",evening:"Buonasera"},
  pl:{morning:"Dzień dobry",afternoon:"Dzień dobry",evening:"Dobry wieczór"},
  uk:{morning:"Доброго ранку",afternoon:"Добрий день",evening:"Добрий вечір"}
};

const getGreeting = (lang:LangCode)=>{const hour=new Date().getHours();const g=GREETINGS[lang]||GREETINGS.en;return hour<12?g.morning:hour<18?g.afternoon:g.evening;};

const DAYS_OF_WEEK_MAP = {
  en:[{id:1,label:"Mon"},{id:2,label:"Tue"},{id:3,label:"Wed"},{id:4,label:"Thu"},{id:5,label:"Fri"},{id:6,label:"Sat"},{id:0,label:"Sun"}],
  tr:[{id:1,label:"Pzt"},{id:2,label:"Sal"},{id:3,label:"Çar"},{id:4,label:"Per"},{id:5,label:"Cum"},{id:6,label:"Cmt"},{id:0,label:"Paz"}],
  nl:[{id:1,label:"Ma"},{id:2,label:"Di"},{id:3,label:"Wo"},{id:4,label:"Do"},{id:5,label:"Vr"},{id:6,label:"Za"},{id:0,label:"Zo"}],
  de:[{id:1,label:"Mo"},{id:2,label:"Di"},{id:3,label:"Mi"},{id:4,label:"Do"},{id:5,label:"Fr"},{id:6,label:"Sa"},{id:0,label:"So"}],
  es:[{id:1,label:"Lun"},{id:2,label:"Mar"},{id:3,label:"Mié"},{id:4,label:"Jue"},{id:5,label:"Vie"},{id:6,label:"Sáb"},{id:0,label:"Dom"}],
  fr:[{id:1,label:"Lun"},{id:2,label:"Mar"},{id:3,label:"Mer"},{id:4,label:"Jeu"},{id:5,label:"Ven"},{id:6,label:"Sam"},{id:0,label:"Dim"}],
  ar:[{id:1,label:"الاثنين"},{id:2,label:"الثلاثاء"},{id:3,label:"الأربعاء"},{id:4,label:"الخميس"},{id:5,label:"الجمعة"},{id:6,label:"السبت"},{id:0,label:"الأحد"}],
  id:[{id:1,label:"Sen"},{id:2,label:"Sel"},{id:3,label:"Rab"},{id:4,label:"Kam"},{id:5,label:"Jum"},{id:6,label:"Sab"},{id:0,label:"Min"}],
  pt:[{id:1,label:"Seg"},{id:2,label:"Ter"},{id:3,label:"Qua"},{id:4,label:"Qui"},{id:5,label:"Sex"},{id:6,label:"Sáb"},{id:0,label:"Dom"}],
  hi:[{id:1,label:"सोम"},{id:2,label:"मंगल"},{id:3,label:"बुध"},{id:4,label:"गुरु"},{id:5,label:"शुक्र"},{id:6,label:"शनि"},{id:0,label:"रवि"}],
  ko:[{id:1,label:"월"},{id:2,label:"화"},{id:3,label:"수"},{id:4,label:"목"},{id:5,label:"금"},{id:6,label:"토"},{id:0,label:"일"}],
  ja:[{id:1,label:"月"},{id:2,label:"火"},{id:3,label:"水"},{id:4,label:"木"},{id:5,label:"金"},{id:6,label:"土"},{id:0,label:"日"}],
  ru:[{id:1,label:"Пн"},{id:2,label:"Вт"},{id:3,label:"Ср"},{id:4,label:"Чт"},{id:5,label:"Пт"},{id:6,label:"Сб"},{id:0,label:"Вс"}],
  it:[{id:1,label:"Lun"},{id:2,label:"Mar"},{id:3,label:"Mer"},{id:4,label:"Gio"},{id:5,label:"Ven"},{id:6,label:"Sab"},{id:0,label:"Dom"}],
  pl:[{id:1,label:"Pon"},{id:2,label:"Wto"},{id:3,label:"Śro"},{id:4,label:"Czw"},{id:5,label:"Pią"},{id:6,label:"Sob"},{id:0,label:"Nie"}],
  uk:[{id:1,label:"Пн"},{id:2,label:"Вт"},{id:3,label:"Ср"},{id:4,label:"Чт"},{id:5,label:"Пт"},{id:6,label:"Сб"},{id:0,label:"Нд"}]
};

const getDaysOfWeek = (lang:LangCode)=>DAYS_OF_WEEK_MAP[lang]||DAYS_OF_WEEK_MAP.en;
